/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_ComplexEnum */

#ifndef _Included_jni_ComplexEnum
#define _Included_jni_ComplexEnum
#ifdef __cplusplus
extern "C" {
#endif
#undef jni_ComplexEnum_serialVersionUID
#define jni_ComplexEnum_serialVersionUID 8476000850333817230LL
#ifdef __cplusplus
}
#endif
#endif
