/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Cube */

#ifndef _Included_jni_Cube
#define _Included_jni_Cube
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Cube
 * Method:    drawFaceN
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_jni_Cube_drawFaceN
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     jni_Cube
 * Method:    activateShader
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jni_Cube_activateShader
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
