/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Shape */

#ifndef _Included_jni_Shape
#define _Included_jni_Shape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Shape
 * Method:    drawN
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_jni_Shape_drawN
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     jni_Shape
 * Method:    bindBufferN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jni_Shape_bindBufferN
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
