/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Viewport */

#ifndef _Included_jni_Viewport
#define _Included_jni_Viewport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Viewport
 * Method:    drawImage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jni_Viewport_drawImage
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
