/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Framebuffer */

#ifndef _Included_jni_Framebuffer
#define _Included_jni_Framebuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Framebuffer
 * Method:    setupN
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_jni_Framebuffer_setupN
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     jni_Framebuffer
 * Method:    getTextureIDN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_Framebuffer_getTextureIDN
  (JNIEnv *, jobject);

/*
 * Class:     jni_Framebuffer
 * Method:    startN
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jni_Framebuffer_startN
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jni_Framebuffer
 * Method:    endN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_Framebuffer_endN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
