/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_SkyBox */

#ifndef _Included_jni_SkyBox
#define _Included_jni_SkyBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_SkyBox
 * Method:    drawN
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_jni_SkyBox_drawN
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jni_SkyBox
 * Method:    bindBufferN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_SkyBox_bindBufferN
  (JNIEnv *, jobject);

/*
 * Class:     jni_SkyBox
 * Method:    activateShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jni_SkyBox_activateShader
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
