/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Cube */

#ifndef _Included_jni_Cube
#define _Included_jni_Cube
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Cube
 * Method:    drawFaceN
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_jni_Cube_drawFaceN
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     jni_Cube
 * Method:    drawFaceManyN
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_jni_Cube_drawFaceManyN
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     jni_Cube
 * Method:    drawItemFaceN
 * Signature: (FFIII)V
 */
JNIEXPORT void JNICALL Java_jni_Cube_drawItemFaceN
  (JNIEnv *, jobject, jfloat, jfloat, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
