/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_GLWrapper */

#ifndef _Included_jni_GLWrapper
#define _Included_jni_GLWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_GLWrapper
 * Method:    preInit
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_preInit
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     jni_GLWrapper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_init
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    shouldClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jni_GLWrapper_shouldClose
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_close
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    deltaT
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jni_GLWrapper_deltaT
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    processInput
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_processInput
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     jni_GLWrapper
 * Method:    prerender
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_prerender
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     jni_GLWrapper
 * Method:    postrender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_postrender
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    swapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_swapBuffers
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    pollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_pollEvents
  (JNIEnv *, jclass);

/*
 * Class:     jni_GLWrapper
 * Method:    generateTexture
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_jni_GLWrapper_generateTexture
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     jni_GLWrapper
 * Method:    useTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_useTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jni_GLWrapper
 * Method:    checkError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_GLWrapper_checkError
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
