/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Utilities */

#ifndef _Included_jni_Utilities
#define _Included_jni_Utilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Utilities
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_Utilities_getValue
  (JNIEnv *, jobject);

/*
 * Class:     jni_Utilities
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_Utilities_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
